/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/weather/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_api_weather_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Forecast */
        get: operations["forecast_api_weather_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/weather/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_weather_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/atlas/{timestamp}/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Atlas Tile
         * @description Serve a 256×2048 grayscale PNG atlas tile with 8 tilt bands.
         */
        get: operations["radar_atlas_tile_api_radar_atlas__timestamp___z___x___y__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/atlas-raw/{timestamp}/{z}/{x}/{y}.bin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Atlas Tile Raw
         * @description Serve a 256×2048 single-channel uint8 atlas tile as raw bytes.
         *
         *     Identical payload to the ``.png`` endpoint but undecoded, so React Native
         *     (which lacks ``createImageBitmap``/canvas) can upload it straight to an R8
         *     ``DataTexture`` without a client-side PNG decode.
         */
        get: operations["radar_atlas_tile_raw_api_radar_atlas_raw__timestamp___z___x___y__bin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/motion/{timestamp}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Motion Tile
         * @description Serve the motion vector field for *timestamp* → next frame as RGB PNG.
         */
        get: operations["radar_motion_tile_api_radar_motion__timestamp__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/motion-raw/{timestamp}.bin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Motion Tile Raw
         * @description Serve the motion field as raw RGB bytes (for native DataTexture upload).
         *
         *     Decodes the stored motion PNG server-side so React Native doesn't need a PNG
         *     decoder. Width/height are returned in the X-Width / X-Height headers.
         */
        get: operations["radar_motion_tile_raw_api_radar_motion_raw__timestamp__bin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/timestamps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Timestamps
         * @description Return the list of available radar timestamps with motion availability.
         */
        get: operations["radar_timestamps_api_radar_timestamps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/radar/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Radar Refresh
         * @description Force cache invalidation and re-seed.
         */
        get: operations["radar_refresh_api_radar_refresh_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Config
         * @description Return frontend configuration (basemap tile API keys, default station).
         */
        get: operations["api_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness probe: returns 200 once frames are available, 503 during seeding.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** No Web */
        get: operations["_no_web__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CurrentObservation */
        CurrentObservation: {
            /** Stationid */
            stationId: string;
            /** Neighborhood */
            neighborhood?: string | null;
            /** Observationtime */
            observationTime: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Temp */
            temp?: number | null;
            /** Feelslike */
            feelsLike?: number | null;
            /** Dewpoint */
            dewPoint?: number | null;
            /** Humidity */
            humidity?: number | null;
            /** Pressure */
            pressure?: number | null;
            /** Preciprate */
            precipRate?: number | null;
            /** Preciptotal */
            precipTotal?: number | null;
            /** Windspeed */
            windSpeed?: number | null;
            /** Winddir */
            windDir?: number | null;
            /** Windgust */
            windGust?: number | null;
            /** Uv */
            uv?: number | null;
            /** Solarradiation */
            solarRadiation?: number | null;
            /**
             * Units
             * @enum {string}
             */
            units: "e" | "m";
        };
        /** CurrentObservationResponse */
        CurrentObservationResponse: {
            data: components["schemas"]["CurrentObservation"];
        };
        /** ForecastDay */
        ForecastDay: {
            /** Dayofweek */
            dayOfWeek: string;
            /** Validdate */
            validDate: string;
            /** Dayicon */
            dayIcon?: number | null;
            /** Dayphrase */
            dayPhrase?: string | null;
            /** Dayprecipchance */
            dayPrecipChance?: number | null;
            /** Daytemp */
            dayTemp?: number | null;
            /** Dayhumidity */
            dayHumidity?: number | null;
            /** Daywindspeed */
            dayWindSpeed?: number | null;
            /** Daywinddir */
            dayWindDir?: string | null;
            /** Nighticon */
            nightIcon?: number | null;
            /** Nightphrase */
            nightPhrase?: string | null;
            /** Nightprecipchance */
            nightPrecipChance?: number | null;
            /** Nighttemp */
            nightTemp?: number | null;
            /** Nighthumidity */
            nightHumidity?: number | null;
            /** Nightwindspeed */
            nightWindSpeed?: number | null;
            /** Nightwinddir */
            nightWindDir?: string | null;
            /** Temphigh */
            tempHigh?: number | null;
            /** Templow */
            tempLow?: number | null;
            /** Sunrise */
            sunrise?: string | null;
            /** Sunset */
            sunset?: string | null;
            /** Moonphase */
            moonPhase?: string | null;
        };
        /** ForecastResponse */
        ForecastResponse: {
            /** Data */
            data: components["schemas"]["ForecastDay"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryDay */
        HistoryDay: {
            /** Date */
            date: string;
            /** Temphigh */
            tempHigh?: number | null;
            /** Templow */
            tempLow?: number | null;
            /** Tempavg */
            tempAvg?: number | null;
            /** Preciptotal */
            precipTotal?: number | null;
            /** Humidityhigh */
            humidityHigh?: number | null;
            /** Humiditylow */
            humidityLow?: number | null;
            /** Windspeedavg */
            windSpeedAvg?: number | null;
            /** Windspeedhigh */
            windSpeedHigh?: number | null;
            /** Pressuremax */
            pressureMax?: number | null;
            /** Pressuremin */
            pressureMin?: number | null;
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Data */
            data: components["schemas"]["HistoryDay"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    current_api_weather_current_get: {
        parameters: {
            query: {
                stationId: string;
                units?: "e" | "m";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentObservationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_api_weather_forecast_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                units?: "e" | "m";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    history_api_weather_history_get: {
        parameters: {
            query: {
                stationId: string;
                units?: "e" | "m";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_atlas_tile_api_radar_atlas__timestamp___z___x___y__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timestamp: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_atlas_tile_raw_api_radar_atlas_raw__timestamp___z___x___y__bin_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timestamp: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_motion_tile_api_radar_motion__timestamp__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_motion_tile_raw_api_radar_motion_raw__timestamp__bin_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                timestamp: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    radar_timestamps_api_radar_timestamps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    radar_refresh_api_radar_refresh_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    api_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    _no_web__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
